-- Keep the web repository aligned with the mobile app's shared Supabase schema.
alter table public.products
  add column if not exists low_stock_threshold integer not null default 3
  check (low_stock_threshold >= 0);

alter table public.customers
  add column if not exists customer_number bigint generated by default as identity,
  add column if not exists preferred_order_type text not null default 'immediate'
  check (preferred_order_type in ('immediate', 'preorder'));

create unique index if not exists customers_store_customer_number_key
  on public.customers(store_id, customer_number);

create table if not exists public.inventory_movements (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  previous_stock integer not null,
  new_stock integer not null,
  quantity_change integer not null,
  reason text not null default 'stock_adjustment',
  created_by_profile_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists inventory_movements_store_created_idx
  on public.inventory_movements(store_id, created_at desc);
create index if not exists inventory_movements_product_created_idx
  on public.inventory_movements(product_id, created_at desc);

alter table public.inventory_movements enable row level security;

drop policy if exists "inventory_movements_owner_select" on public.inventory_movements;
create policy "inventory_movements_owner_select"
  on public.inventory_movements for select
  using (public.is_store_owner(store_id));

create or replace function public.log_product_stock_movement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.stock is distinct from new.stock then
    insert into public.inventory_movements(
      store_id, product_id, previous_stock, new_stock, quantity_change,
      reason, created_by_profile_id
    ) values (
      new.store_id, new.id, old.stock, new.stock, new.stock - old.stock,
      case
        when new.stock > old.stock then 'stock_in'
        when new.stock < old.stock then 'stock_out'
        else 'stock_adjustment'
      end,
      auth.uid()
    );
  end if;
  return new;
end;
$$;

drop trigger if exists products_log_stock_movement on public.products;
create trigger products_log_stock_movement
after update of stock on public.products
for each row execute function public.log_product_stock_movement();
